# Q. What is this file?
# A. This file contains options which allow you to configure your multiworld experience while allowing
#    others to play how they want as well.
#
# Q. How do I use it?
# A. The options in this file are weighted. This means the higher number you assign to a value, the
#    more chances you have for that option to be chosen. For example, an option like this:
#
#    map_shuffle:
#      on: 5
#      off: 15
#
#    Means you have 5 chances for map shuffle to occur, and 15 chances for map shuffle to be turned
#    off.
#
# Q. I've never seen a file like this before. What characters am I allowed to use?
# A. This is a .yaml file. You are allowed to use most characters.
#    To test if your yaml is valid or not, you can use this website:
#        http://www.yamllint.com/
#    You can also verify your Archipelago settings are valid at this site:
#        https://archipelago.gg/check

# Your name in-game. Spaces will be replaced with underscores and there is a 16-character limit.
#     {player} will be replaced with the player's slot number.
#     {PLAYER} will be replaced with the player's slot number, if that slot number is greater than 1.
#     {number} will be replaced with the counter value of the name.
#     {NUMBER} will be replaced with the counter value of the name, if the counter value is greater than 1.
name: Player{number}

# Used to describe your yaml. Useful if you have multiple files.
description: Default A Link to the Past Template

game: A Link to the Past
requires:
  version: 0.3.9 # Version of Archipelago required for this yaml to work as expected.

A Link to the Past:
  progression_balancing:
    # A system that can move progression earlier, to try and prevent the player from getting stuck and bored early.
    # A lower setting means more getting stuck. A higher setting means less getting stuck.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 99
    random: 0
    random-low: 0
    random-high: 0
    disabled: 0 # equivalent to 0
    normal: 50 # equivalent to 50
    extreme: 0 # equivalent to 99

  accessibility:
    # Set rules for reachability of your items/locations.
    # Locations: ensure everything can be reached and acquired.
    # Items: ensure all logically relevant items can be acquired.
    # Minimal: ensure what is needed to reach your goal can be acquired.
    locations: 0
    items: 50
    minimal: 0

  local_items:
    # Forces these items to be in their native world.
    []

  non_local_items:
    # Forces these items to be outside their native world.
    []

  start_inventory:
    # Start with these items.
    {}

  start_hints:
    # Start with these item's locations prefilled into the !hint command.
    []

  start_location_hints:
    # Start with these locations and their item prefilled into the !hint command
    []

  exclude_locations:
    # Prevent these locations from having an important item
    []

  priority_locations:
    # Prevent these locations from having an unimportant item
    []

  item_links:
    # Share part of your item pool with other players.
    []

  crystals_needed_for_gt:
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 7
    7: 50
    random: 0
    random-low: 0
    random-high: 0

  crystals_needed_for_ganon:
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 7
    7: 50
    random: 0
    random-low: 0
    random-high: 0

  open_pyramid:
    # Determines whether the hole at the top of pyramid is open.
    # Goal will open the pyramid if the goal requires you to kill Ganon, without needing to kill Agahnim 2.
    # Auto is the same as goal except if Ganon's dropdown is in another location, the hole will be closed.
    closed: 0
    open: 0
    goal: 50
    auto: 0

  bigkey_shuffle:
    # Big Key Placement
    original_dungeon: 50
    own_dungeons: 0
    own_world: 0
    any_world: 0
    different_world: 0
    start_with: 0

  smallkey_shuffle:
    # Small Key Placement
    original_dungeon: 50
    own_dungeons: 0
    own_world: 0
    any_world: 0
    different_world: 0
    start_with: 0
    universal: 0

  compass_shuffle:
    # Compass Placement
    original_dungeon: 50
    own_dungeons: 0
    own_world: 0
    any_world: 0
    different_world: 0
    start_with: 0

  map_shuffle:
    # Map Placement
    original_dungeon: 50
    own_dungeons: 0
    own_world: 0
    any_world: 0
    different_world: 0
    start_with: 0

  progressive:
    off: 0
    grouped_random: 0
    on: 50

  swordless:
    # No swords. Curtains in Skull Woods and Agahnim's
    # Tower are removed, Agahnim's Tower barrier can be
    # destroyed with hammer. Misery Mire and Turtle Rock
    # can be opened without a sword. Hammer damages Ganon.
    # Ether and Bombos Tablet can be activated with Hammer
    # (and Book).
    false: 50
    true: 0

  retro_bow:
    # Zelda-1 like mode. You have to purchase a quiver to shoot arrows using rupees.
    false: 50
    true: 0

  retro_caves:
    # Zelda-1 like mode. There are randomly placed take-any caves that contain one Sword and
    # choices of Heart Container/Blue Potion.
    false: 50
    true: 0

  hints:
    # On/Full: Put item and entrance placement hints on telepathic tiles and some NPCs, Full removes joke hints.
    off: 0
    on: 50
    full: 0

  scams:
    # If on, these Merchants will no longer tell you what they're selling.
    off: 50
    king_zora: 0
    bottle_merchant: 0
    all: 0

  restrict_dungeon_item_on_boss:
    # Don't place dungeon-native items on the dungeon's boss.
    false: 50
    true: 0

  boss_shuffle:
    # Shuffles bosses around to different locations.
    # Basic will shuffle all bosses except Ganon and Agahnim anywhere they can be placed.
    # Full chooses 3 bosses at random to be placed twice instead of Lanmolas, Moldorm, and Helmasaur.
    # Chaos allows any boss to appear any number of times.
    # Singularity places a single boss in as many places as possible, and a second boss in any remaining locations.
    # Supports plando placement. Formatting here: https://archipelago.gg/tutorial/A%20Link%20to%20the%20Past/plando/en
    none: 50
    basic: 0
    full: 0
    chaos: 0
    singularity: 0

  pot_shuffle:
    # Shuffle contents of pots within "supertiles" (item will still be nearby original placement).
    false: 50
    true: 0

  enemy_shuffle:
    # Randomize every enemy spawn.
    # If mode is Standard, Hyrule Castle is left out (may result in visually wrong enemy sprites in that area.)
    false: 50
    true: 0

  killable_thieves:
    # Makes Thieves killable.
    false: 50
    true: 0

  bush_shuffle:
    # Randomize chance that a bush contains an enemy as well as which enemy may spawn.
    false: 50
    true: 0

  shop_item_slots:
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 30
    0: 50
    random: 0
    random-low: 0
    random-high: 0

  shop_price_modifier:
    # Percentage modifier for shuffled item prices in shops
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 400
    100: 50
    random: 0
    random-low: 0
    random-high: 0

  tile_shuffle:
    # Randomize flying tiles floor patterns.
    false: 50
    true: 0

  ow_palettes:
    default: 50
    good: 0
    blackout: 0
    puke: 0
    classic: 0
    grayscale: 0
    negative: 0
    dizzy: 0
    sick: 0

  uw_palettes:
    default: 50
    good: 0
    blackout: 0
    puke: 0
    classic: 0
    grayscale: 0
    negative: 0
    dizzy: 0
    sick: 0

  hud_palettes:
    default: 50
    good: 0
    blackout: 0
    puke: 0
    classic: 0
    grayscale: 0
    negative: 0
    dizzy: 0
    sick: 0

  sword_palettes:
    default: 50
    good: 0
    blackout: 0
    puke: 0
    classic: 0
    grayscale: 0
    negative: 0
    dizzy: 0
    sick: 0

  shield_palettes:
    default: 50
    good: 0
    blackout: 0
    puke: 0
    classic: 0
    grayscale: 0
    negative: 0
    dizzy: 0
    sick: 0

  heartbeep:
    normal: 50
    double: 0
    half: 0
    quarter: 0
    off: 0

  heartcolor:
    red: 50
    blue: 0
    green: 0
    yellow: 0

  quickswap:
    false: 0
    true: 50

  menuspeed:
    normal: 50
    instant: 0
    double: 0
    triple: 0
    quadruple: 0
    half: 0

  music:
    false: 0
    true: 50

  reduceflashing:
    false: 0
    true: 50

  triforcehud:
    normal: 50
    hide_goal: 0
    hide_required: 0
    hide_both: 0

  glitch_boots:
    false: 0
    true: 50

  beemizer_total_chance:
    # Percentage chance for each junk-fill item (rupees, bombs, arrows) to be
    # replaced with either a bee swarm trap or a single bottle-filling bee.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 100
    0: 50
    random: 0
    random-low: 0
    random-high: 0

  beemizer_trap_chance:
    # Percentage chance for each replaced junk-fill item to be a bee swarm
    # trap; all other replaced items are single bottle-filling bees.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 100
    60: 50
    random: 0
    random-low: 0
    random-high: 0

  death_link:
    # When you die, everyone dies. Of course the reverse is true too.
    false: 50
    true: 0

  allow_collect:
    # Allows for !collect / co-op to auto-open chests containing items for other players.
    # Off by default, because it currently crashes on real hardware.
    false: 50
    true: 0
