# Q. What is this file?
# A. This file contains options which allow you to configure your multiworld experience while allowing
#    others to play how they want as well.
#
# Q. How do I use it?
# A. The options in this file are weighted. This means the higher number you assign to a value, the
#    more chances you have for that option to be chosen. For example, an option like this:
#
#    map_shuffle:
#      on: 5
#      off: 15
#
#    Means you have 5 chances for map shuffle to occur, and 15 chances for map shuffle to be turned
#    off.
#
# Q. I've never seen a file like this before. What characters am I allowed to use?
# A. This is a .yaml file. You are allowed to use most characters.
#    To test if your yaml is valid or not, you can use this website:
#        http://www.yamllint.com/
#    You can also verify your Archipelago settings are valid at this site:
#        https://archipelago.gg/check

# Your name in-game. Spaces will be replaced with underscores and there is a 16-character limit.
#     {player} will be replaced with the player's slot number.
#     {PLAYER} will be replaced with the player's slot number, if that slot number is greater than 1.
#     {number} will be replaced with the counter value of the name.
#     {NUMBER} will be replaced with the counter value of the name, if the counter value is greater than 1.
name: Player{number}

# Used to describe your yaml. Useful if you have multiple files.
description: Default Dark Souls III Template

game: Dark Souls III
requires:
  version: 0.3.9 # Version of Archipelago required for this yaml to work as expected.

Dark Souls III:
  progression_balancing:
    # A system that can move progression earlier, to try and prevent the player from getting stuck and bored early.
    # A lower setting means more getting stuck. A higher setting means less getting stuck.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 99
    random: 0
    random-low: 0
    random-high: 0
    disabled: 0 # equivalent to 0
    normal: 50 # equivalent to 50
    extreme: 0 # equivalent to 99

  accessibility:
    # Set rules for reachability of your items/locations.
    # Locations: ensure everything can be reached and acquired.
    # Items: ensure all logically relevant items can be acquired.
    # Minimal: ensure what is needed to reach your goal can be acquired.
    locations: 0
    items: 50
    minimal: 0

  local_items:
    # Forces these items to be in their native world.
    []

  non_local_items:
    # Forces these items to be outside their native world.
    []

  start_inventory:
    # Start with these items.
    {}

  start_hints:
    # Start with these item's locations prefilled into the !hint command.
    []

  start_location_hints:
    # Start with these locations and their item prefilled into the !hint command
    []

  exclude_locations:
    # Prevent these locations from having an important item
    []

  priority_locations:
    # Prevent these locations from having an unimportant item
    []

  item_links:
    # Share part of your item pool with other players.
    []

  auto_equip:
    # Automatically equips any received armor or left/right weapons.
    false: 50
    true: 0

  lock_equip:
    # Lock the equipment slots so you cannot change your armor or your left/right weapons. Works great with the
    # Auto-equip option.
    false: 50
    true: 0

  no_weapon_requirements:
    # Disable the weapon requirements by removing any movement or damage penalties.
    # Permitting you to use any weapon early
    false: 50
    true: 0

  randomize_weapons_level:
    # Enable this option to upgrade a percentage of the pool of weapons to a random value between the minimum and 
    # maximum levels defined. 
    # all: All weapons are eligible, both basic and epic
    # basic: Only weapons that can be upgraded to +10
    # epic: Only weapons that can be upgraded to +5
    none: 50
    all: 0
    basic: 0
    epic: 0

  randomize_weapons_percentage:
    # The percentage of weapons in the pool to be upgraded if randomize weapons level is toggled
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 1
    # Maximum value is 100
    33: 50
    random: 0
    random-low: 0
    random-high: 0

  min_levels_in_5:
    # The minimum upgraded value of a weapon in the pool of weapons that can only reach +5
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 1
    # Maximum value is 5
    1: 50
    random: 0
    random-low: 0
    random-high: 0

  max_levels_in_5:
    # The maximum upgraded value of a weapon in the pool of weapons that can only reach +5
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 1
    # Maximum value is 5
    5: 50
    random: 0
    random-low: 0
    random-high: 0

  min_levels_in_10:
    # The minimum upgraded value of a weapon in the pool of weapons that can reach +10
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 1
    # Maximum value is 10
    1: 50
    random: 0
    random-low: 0
    random-high: 0

  max_levels_in_10:
    # The maximum upgraded value of a weapon in the pool of weapons that can reach +10
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 1
    # Maximum value is 10
    10: 50
    random: 0
    random-low: 0
    random-high: 0

  late_basin_of_vows:
    # Force the Basin of Vows to be located as a reward of defeating Pontiff Sulyvahn. It permits to ease the
    # progression by preventing having to kill the Dancer of the Boreal Valley as the first boss
    false: 50
    true: 0

  no_spell_requirements:
    # Disable the spell requirements permitting you to use any spell
    false: 50
    true: 0

  no_equip_load:
    # Disable the equip load constraint from the game
    false: 50
    true: 0

  death_link:
    # When you die, everyone dies. Of course the reverse is true too.
    false: 50
    true: 0
