# Q. What is this file?
# A. This file contains options which allow you to configure your multiworld experience while allowing
#    others to play how they want as well.
#
# Q. How do I use it?
# A. The options in this file are weighted. This means the higher number you assign to a value, the
#    more chances you have for that option to be chosen. For example, an option like this:
#
#    map_shuffle:
#      on: 5
#      off: 15
#
#    Means you have 5 chances for map shuffle to occur, and 15 chances for map shuffle to be turned
#    off.
#
# Q. I've never seen a file like this before. What characters am I allowed to use?
# A. This is a .yaml file. You are allowed to use most characters.
#    To test if your yaml is valid or not, you can use this website:
#        http://www.yamllint.com/
#    You can also verify your Archipelago settings are valid at this site:
#        https://archipelago.gg/check

# Your name in-game. Spaces will be replaced with underscores and there is a 16-character limit.
#     {player} will be replaced with the player's slot number.
#     {PLAYER} will be replaced with the player's slot number, if that slot number is greater than 1.
#     {number} will be replaced with the counter value of the name.
#     {NUMBER} will be replaced with the counter value of the name, if the counter value is greater than 1.
name: Player{number}

# Used to describe your yaml. Useful if you have multiple files.
description: Default Kingdom Hearts 2 Template

game: Kingdom Hearts 2
requires:
  version: 0.3.9 # Version of Archipelago required for this yaml to work as expected.

Kingdom Hearts 2:
  progression_balancing:
    # A system that can move progression earlier, to try and prevent the player from getting stuck and bored early.
    # A lower setting means more getting stuck. A higher setting means less getting stuck.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 99
    random: 0
    random-low: 0
    random-high: 0
    disabled: 0 # equivalent to 0
    normal: 50 # equivalent to 50
    extreme: 0 # equivalent to 99

  accessibility:
    # Set rules for reachability of your items/locations.
    # Locations: ensure everything can be reached and acquired.
    # Items: ensure all logically relevant items can be acquired.
    # Minimal: ensure what is needed to reach your goal can be acquired.
    locations: 0
    items: 50
    minimal: 0

  local_items:
    # Forces these items to be in their native world.
    []

  non_local_items:
    # Forces these items to be outside their native world.
    []

  start_inventory:
    # Start with these items.
    {}

  start_hints:
    # Start with these item's locations prefilled into the !hint command.
    []

  start_location_hints:
    # Start with these locations and their item prefilled into the !hint command
    []

  exclude_locations:
    # Prevent these locations from having an important item
    []

  priority_locations:
    # Prevent these locations from having an unimportant item
    []

  item_links:
    # Share part of your item pool with other players.
    []

  Sora_Level_EXP:
    # Sora Level Exp Multiplier
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 1
    # Maximum value is 10
    5: 50
    random: 0
    random-low: 0
    random-high: 0

  Final_Form_EXP:
    # Final Form Exp Multiplier
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 1
    # Maximum value is 10
    3: 50
    random: 0
    random-low: 0
    random-high: 0

  Master_Form_EXP:
    # Master Form Exp Multiplier
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 1
    # Maximum value is 10
    3: 50
    random: 0
    random-low: 0
    random-high: 0

  Limit_Form_EXP:
    # Limit Form Exp Multiplier
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 1
    # Maximum value is 10
    3: 50
    random: 0
    random-low: 0
    random-high: 0

  Wisdom_Form_EXP:
    # Wisdom Form Exp Multiplier
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 1
    # Maximum value is 10
    3: 50
    random: 0
    random-low: 0
    random-high: 0

  Valor_Form_EXP:
    # Valor Form Exp Multiplier
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 1
    # Maximum value is 10
    3: 50
    random: 0
    random-low: 0
    random-high: 0

  Summon_EXP:
    # Summon Exp Multiplier
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 1
    # Maximum value is 10
    5: 50
    random: 0
    random-low: 0
    random-high: 0

  Schmovement:
    # Level of Growth You Start With
    level_0: 0
    level_1: 50
    level_2: 0
    level_3: 0
    level_4: 0

  Keyblade_Minimum:
    # Minimum Stats for the Keyblade
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 20
    3: 50
    random: 0
    random-low: 0
    random-high: 0

  Keyblade_Maximum:
    # Maximum Stats for the Keyblade
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 20
    7: 50
    random: 0
    random-low: 0
    random-high: 0

  Visitlocking:
    # Determines the level of visit locking
    # No Visit Locking:No visit locks(everything is sphere 1.Not Recommended)# BK is making a lot of money
    # Second Visit Locking:Start with 13 visit locking items for every first visit
    # First and Second Visit Locking:One item for First Visit Two For Second Visit
    no_visit_locking: 0
    second_visit_locking: 0
    first_and_second_visit_locking: 50

  RandomVisitLockingItem:
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 27
    3: 50
    random: 0
    random-low: 0
    random-high: 0

  SuperBosses:
    # Terra, Sephiroth and Data Fights Toggle.
    false: 50
    true: 0

  LevelDepth:
    # Determines How many locations you want on levels
    # Level 50:23 checks spread through 50 levels
    # Level 99:23 checks spread through 99 levels
    # Level 50 sanity:check per level for 50 levels
    # Level 99 sanity:check per level for 99 levels
    # Level 1: no checks on levels(checks are replaced with stats)
    level_50: 50
    level_99: 0
    level_50_sanity: 0
    level_99_sanity: 0
    level_1: 0

  Promise_Charm:
    # Add Promise Charm to the Pool
    false: 50
    true: 0

  KeybladeAbilities:
    # Action:Has Action Abilities on Keyblades
    # Support:Has Support Abilities on Keyblades
    support: 0
    action: 0
    both: 50

  BlacklistKeyblade:
    # Black List these Abilities on Keyblades
    []

  RandomGrowth:
    # Amount of Random Growth Abilities You Start With
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 20
    0: 50
    random: 0
    random-low: 0
    random-high: 0

  Goal:
    # Win Condition
    # Three Proofs: Obtain the Three Proofs and Have a Gold Crown on Sora's Head.
    # Lucky Emblem Hunt: Acquire The Amount of Lucky Emblems you have set.
    # Hitlist: Kill the Superbosses on the "Hitlist" then synth ultima weapon.
    three_proofs: 50
    lucky_emblem_hunt: 0
    hitlist: 0

  FinalXemnas:
    # Kill Final Xemnas to Beat the Game.
    # This is in addition to your Goal. I.E. get three proofs+kill final Xemnas
    false: 0
    true: 50

  LuckyEmblemsAmount:
    # Number of Lucky Emblems that are in the pool.
    # If Goal is not Lucky Emblem Hunt this does nothing.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 60
    40: 50
    random: 0
    random-low: 0
    random-high: 0

  LuckyEmblemsRequired:
    # Number of Lucky Emblems to collect to Open The Final Door bosses.
    # If Goal is not Lucky Emblem Hunt this does nothing.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 60
    25: 50
    random: 0
    random-low: 0
    random-high: 0

  BountyAmount:
    # Number of Bounties that are in the pool.
    #     If Goal is not Hitlist this does nothing.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 24
    13: 50
    random: 0
    random-low: 0
    random-high: 0

  BountyRequired:
    # Number of Bounties that are Required.
    #     If Goal is not Hitlist this does nothing.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 24
    7: 50
    random: 0
    random-low: 0
    random-high: 0

  Cups:
    # Olympus Cups Toggles
    #     No Cups: No Cups.
    #     Cups: Has every cup except Paradox.
    #     Cups and Hades Paradox: Has Every Cup On.
    no_cups: 0
    cups: 50
    cups_and_hades_paradox: 0
