# Q. What is this file?
# A. This file contains options which allow you to configure your multiworld experience while allowing
#    others to play how they want as well.
#
# Q. How do I use it?
# A. The options in this file are weighted. This means the higher number you assign to a value, the
#    more chances you have for that option to be chosen. For example, an option like this:
#
#    map_shuffle:
#      on: 5
#      off: 15
#
#    Means you have 5 chances for map shuffle to occur, and 15 chances for map shuffle to be turned
#    off.
#
# Q. I've never seen a file like this before. What characters am I allowed to use?
# A. This is a .yaml file. You are allowed to use most characters.
#    To test if your yaml is valid or not, you can use this website:
#        http://www.yamllint.com/
#    You can also verify your Archipelago settings are valid at this site:
#        https://archipelago.gg/check

# Your name in-game. Spaces will be replaced with underscores and there is a 16-character limit.
#     {player} will be replaced with the player's slot number.
#     {PLAYER} will be replaced with the player's slot number, if that slot number is greater than 1.
#     {number} will be replaced with the counter value of the name.
#     {NUMBER} will be replaced with the counter value of the name, if the counter value is greater than 1.
name: Player{number}

# Used to describe your yaml. Useful if you have multiple files.
description: Default Links Awakening DX Template

game: Links Awakening DX
requires:
  version: 0.3.9 # Version of Archipelago required for this yaml to work as expected.

Links Awakening DX:
  progression_balancing:
    # A system that can move progression earlier, to try and prevent the player from getting stuck and bored early.
    # A lower setting means more getting stuck. A higher setting means less getting stuck.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 99
    random: 0
    random-low: 0
    random-high: 0
    disabled: 0 # equivalent to 0
    normal: 50 # equivalent to 50
    extreme: 0 # equivalent to 99

  accessibility:
    # Set rules for reachability of your items/locations.
    # Locations: ensure everything can be reached and acquired.
    # Items: ensure all logically relevant items can be acquired.
    # Minimal: ensure what is needed to reach your goal can be acquired.
    locations: 0
    items: 50
    minimal: 0

  local_items:
    # Forces these items to be in their native world.
    []

  non_local_items:
    # Forces these items to be outside their native world.
    []

  start_inventory:
    # Start with these items.
    {}

  start_hints:
    # Start with these item's locations prefilled into the !hint command.
    []

  start_location_hints:
    # Start with these locations and their item prefilled into the !hint command
    []

  exclude_locations:
    # Prevent these locations from having an important item
    []

  priority_locations:
    # Prevent these locations from having an unimportant item
    []

  item_links:
    # Share part of your item pool with other players.
    []

  logic:
    # Affects where items are allowed to be placed.
    # [Casual] Same as normal, except that a few more complex options are removed, like removing bushes with powder and killing enemies with powder or bombs.
    # [Normal] Playable without using any tricks or glitches. Can require knowledge from a vanilla playthrough, such as how to open Color Dungeon.
    # [Hard] More advanced techniques may be required, but glitches are not. Examples include tricky jumps, killing enemies with only pots.
    # [Glitched] Advanced glitches and techniques may be required, but extremely difficult or tedious tricks are not required. Examples include Bomb Triggers, Super Jumps and Jesus Jumps.
    # [Hell] Obscure knowledge and hard techniques may be required. Examples include featherless jumping with boots and/or hookshot, sequential pit buffers and unclipped superjumps. Things in here can be extremely hard to do or very time consuming.
    normal: 50
    hard: 0
    glitched: 0
    hell: 0

  tradequest:
    # On - adds the trade items to the pool (the trade locations will always be local items)
    # Off - (default) doesn't add them
    false: 50
    true: 0

  experimental_dungeon_shuffle:
    # [WARNING] Experimental, may break generation
    # Randomizes
    false: 50
    true: 0

  experimental_entrance_shuffle:
    # [WARNING] Experimental, may break generation
    # Randomizes where overworld entrances lead to.
    # [Simple] Single-entrance caves/houses that have items are shuffled amongst each other.
    # [Advanced] Simple, but two-way connector caves are shuffled in their own pool as well.
    # [Expert] Advanced, but caves/houses without items are also shuffled into the Simple entrance pool.
    # [Insanity] Expert, but the Raft Minigame hut and Mamu's cave are added to the non-connector pool.
    # If random start location and/or dungeon shuffle is enabled, then these will be shuffled with all the non-connector entrance pool.
    # Note, some entrances can lead into water, use the warp-to-home from the save&quit menu to escape this.
    none: 50
    simple: 0
    advanced: 0
    expert: 0
    insanity: 0

  goal:
    # [Instruments] The Wind Fish's Egg will only open if you have the required number of Instruments of the Sirens, and play the Ballad of the Wind Fish.
    # [Seashells] The Egg will open when you bring 20 seashells. The Ballad and Ocarina are not needed.
    # [Open] The Egg will start pre-opened.
    instruments: 50
    seashells: 0
    open: 0

  instrument_count:
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 8
    8: 50
    random: 0
    random-low: 0
    random-high: 0

  link_palette:
    # A-D are color palettes usually used during the damage animation and can change based on where you are.
    normal: 50
    green: 0
    yellow: 0
    red: 0
    blue: 0
    invert_a: 0
    invert_b: 0
    invert_c: 0
    invert_d: 0

  trendy_game:
    # [Easy] All of the items hold still for you
    # [Normal] The vanilla behavior
    # [Hard] ?
    # [Harder] ???
    # [Hardest] ????
    # [Impossible] ?????
    easy: 0
    normal: 50
    hard: 0
    harder: 0
    hardest: 0
    impossible: 0

  gfxmod:
    # options here correlate with sprite and name files in data/sprites/ladx
    Link: 50

  palette:
    normal: 50
    1bit: 0
    2bit: 0
    greyscale: 0
    pink: 0
    inverted: 0

  shuffle_nightmare_keys:
    # Shuffle Nightmare Keys
    original_dungeon: 50
    own_dungeons: 0
    own_world: 0
    any_world: 0
    different_world: 0

  shuffle_small_keys:
    # Shuffle Small Keys
    original_dungeon: 50
    own_dungeons: 0
    own_world: 0
    any_world: 0
    different_world: 0

  shuffle_maps:
    # Shuffle Dungeon Maps
    original_dungeon: 50
    own_dungeons: 0
    own_world: 0
    any_world: 0
    different_world: 0

  shuffle_compasses:
    # Shuffle Dungeon Compasses
    original_dungeon: 50
    own_dungeons: 0
    own_world: 0
    any_world: 0
    different_world: 0

  shuffle_stone_beaks:
    # Shuffle Owl Beaks
    original_dungeon: 50
    own_dungeons: 0
    own_world: 0
    any_world: 0
    different_world: 0
