# Q. What is this file?
# A. This file contains options which allow you to configure your multiworld experience while allowing
#    others to play how they want as well.
#
# Q. How do I use it?
# A. The options in this file are weighted. This means the higher number you assign to a value, the
#    more chances you have for that option to be chosen. For example, an option like this:
#
#    map_shuffle:
#      on: 5
#      off: 15
#
#    Means you have 5 chances for map shuffle to occur, and 15 chances for map shuffle to be turned
#    off.
#
# Q. I've never seen a file like this before. What characters am I allowed to use?
# A. This is a .yaml file. You are allowed to use most characters.
#    To test if your yaml is valid or not, you can use this website:
#        http://www.yamllint.com/
#    You can also verify your Archipelago settings are valid at this site:
#        https://archipelago.gg/check

# Your name in-game. Spaces will be replaced with underscores and there is a 16-character limit.
#     {player} will be replaced with the player's slot number.
#     {PLAYER} will be replaced with the player's slot number, if that slot number is greater than 1.
#     {number} will be replaced with the counter value of the name.
#     {NUMBER} will be replaced with the counter value of the name, if the counter value is greater than 1.
name: Player{number}

# Used to describe your yaml. Useful if you have multiple files.
description: Default Minecraft Template

game: Minecraft
requires:
  version: 0.3.9 # Version of Archipelago required for this yaml to work as expected.

Minecraft:
  progression_balancing:
    # A system that can move progression earlier, to try and prevent the player from getting stuck and bored early.
    # A lower setting means more getting stuck. A higher setting means less getting stuck.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 99
    random: 0
    random-low: 0
    random-high: 0
    disabled: 0 # equivalent to 0
    normal: 50 # equivalent to 50
    extreme: 0 # equivalent to 99

  accessibility:
    # Set rules for reachability of your items/locations.
    # Locations: ensure everything can be reached and acquired.
    # Items: ensure all logically relevant items can be acquired.
    # Minimal: ensure what is needed to reach your goal can be acquired.
    locations: 0
    items: 50
    minimal: 0

  local_items:
    # Forces these items to be in their native world.
    []

  non_local_items:
    # Forces these items to be outside their native world.
    []

  start_inventory:
    # Start with these items.
    {}

  start_hints:
    # Start with these item's locations prefilled into the !hint command.
    []

  start_location_hints:
    # Start with these locations and their item prefilled into the !hint command
    []

  exclude_locations:
    # Prevent these locations from having an important item
    []

  priority_locations:
    # Prevent these locations from having an unimportant item
    []

  item_links:
    # Share part of your item pool with other players.
    []

  advancement_goal:
    # Number of advancements required to spawn bosses.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 95
    40: 50
    random: 0
    random-low: 0
    random-high: 0

  egg_shards_required:
    # Number of dragon egg shards to collect to spawn bosses.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 40
    0: 50
    random: 0
    random-low: 0
    random-high: 0

  egg_shards_available:
    # Number of dragon egg shards available to collect.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 40
    0: 50
    random: 0
    random-low: 0
    random-high: 0

  required_bosses:
    # Bosses which must be defeated to finish the game.
    none: 0
    ender_dragon: 50
    wither: 0
    both: 0

  shuffle_structures:
    # Enables shuffling of villages, outposts, fortresses, bastions, and end cities.
    false: 0
    true: 50

  structure_compasses:
    # Adds structure compasses to the item pool, which point to the nearest indicated structure.
    false: 0
    true: 50

  bee_traps:
    # Replaces a percentage of junk items with bee traps, which spawn multiple angered bees around every player when
    # received.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 100
    0: 50
    random: 0
    random-low: 0
    random-high: 0

  combat_difficulty:
    # Modifies the level of items logically required for exploring dangerous areas and fighting bosses.
    easy: 0
    normal: 50
    hard: 0

  include_hard_advancements:
    # Enables certain RNG-reliant or tedious advancements.
    false: 50
    true: 0

  include_unreasonable_advancements:
    # Enables the extremely difficult advancements "How Did We Get Here?" and "Adventuring Time."
    false: 50
    true: 0

  include_postgame_advancements:
    # Enables advancements that require spawning and defeating the required bosses.
    false: 50
    true: 0

  send_defeated_mobs:
    # Send killed mobs to other Minecraft worlds which have this option enabled.
    false: 50
    true: 0

  starting_items:
    # Start with these items. Each entry should be of this format: {item: "item_name", amount: #, nbt: "nbt_string"}
    []

  death_link:
    # When you die, everyone dies. Of course the reverse is true too.
    false: 50
    true: 0
