# Q. What is this file?
# A. This file contains options which allow you to configure your multiworld experience while allowing
#    others to play how they want as well.
#
# Q. How do I use it?
# A. The options in this file are weighted. This means the higher number you assign to a value, the
#    more chances you have for that option to be chosen. For example, an option like this:
#
#    map_shuffle:
#      on: 5
#      off: 15
#
#    Means you have 5 chances for map shuffle to occur, and 15 chances for map shuffle to be turned
#    off.
#
# Q. I've never seen a file like this before. What characters am I allowed to use?
# A. This is a .yaml file. You are allowed to use most characters.
#    To test if your yaml is valid or not, you can use this website:
#        http://www.yamllint.com/
#    You can also verify your Archipelago settings are valid at this site:
#        https://archipelago.gg/check

# Your name in-game. Spaces will be replaced with underscores and there is a 16-character limit.
#     {player} will be replaced with the player's slot number.
#     {PLAYER} will be replaced with the player's slot number, if that slot number is greater than 1.
#     {number} will be replaced with the counter value of the name.
#     {NUMBER} will be replaced with the counter value of the name, if the counter value is greater than 1.
name: Player{number}

# Used to describe your yaml. Useful if you have multiple files.
description: Default Sonic Adventure 2 Battle Template

game: Sonic Adventure 2 Battle
requires:
  version: 0.3.9 # Version of Archipelago required for this yaml to work as expected.

Sonic Adventure 2 Battle:
  progression_balancing:
    # A system that can move progression earlier, to try and prevent the player from getting stuck and bored early.
    # A lower setting means more getting stuck. A higher setting means less getting stuck.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 99
    random: 0
    random-low: 0
    random-high: 0
    disabled: 0 # equivalent to 0
    normal: 50 # equivalent to 50
    extreme: 0 # equivalent to 99

  accessibility:
    # Set rules for reachability of your items/locations.
    # Locations: ensure everything can be reached and acquired.
    # Items: ensure all logically relevant items can be acquired.
    # Minimal: ensure what is needed to reach your goal can be acquired.
    locations: 0
    items: 50
    minimal: 0

  local_items:
    # Forces these items to be in their native world.
    []

  non_local_items:
    # Forces these items to be outside their native world.
    []

  start_inventory:
    # Start with these items.
    {}

  start_hints:
    # Start with these item's locations prefilled into the !hint command.
    []

  start_location_hints:
    # Start with these locations and their item prefilled into the !hint command
    []

  exclude_locations:
    # Prevent these locations from having an important item
    []

  priority_locations:
    # Prevent these locations from having an unimportant item
    []

  item_links:
    # Share part of your item pool with other players.
    []

  goal:
    # Determines the goal of the seed
    # Biolizard: Finish Cannon's Core and defeat the Biolizard and Finalhazard
    # Chaos Emerald Hunt: Find the Seven Chaos Emeralds and reach Green Hill Zone
    # Finalhazard Chaos Emerald Hunt: Find the Seven Chaos Emeralds and reach Green Hill Zone, then defeat Finalhazard
    biolizard: 50
    chaos_emerald_hunt: 0
    finalhazard_chaos_emerald_hunt: 0

  mission_shuffle:
    # Determines whether missions order will be shuffled per level
    false: 50
    true: 0

  keysanity:
    # Determines whether picking up Chao Keys grants checks
    false: 50
    true: 0

  whistlesanity:
    # Determines whether whistling at various spots grants checks
    # None: No Whistle Spots grant checks
    # Pipes: Whistling at Pipes grants checks
    # Hidden: Whistling at Hidden Whistle Spots grants checks
    # Both: Whistling at both Pipes and Hidden Whistle Spots grants checks
    none: 50
    pipes: 0
    hidden: 0
    both: 0

  beetlesanity:
    # Determines whether destroying Gold Beetles grants checks
    false: 50
    true: 0

  required_rank:
    # Determines what minimum Rank is required to send a check for a mission
    e: 50
    d: 0
    c: 0
    b: 0
    a: 0

  emblem_percentage_for_cannons_core:
    # Allows logic to gate the final mission behind a number of Emblems
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 75
    50: 50
    random: 0
    random-low: 0
    random-high: 0

  required_cannons_core_missions:
    # Determines how many Cannon's Core missions must be completed to unlock the Biolizard (for the "Biolizard" goal)
    # First: Only the first mission must be completed
    # All Active: All active Cannon's Core missions must be completed
    first: 50
    all_active: 0

  number_of_level_gates:
    # The number emblem-locked gates which lock sets of levels
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 5
    3: 50
    random: 0
    random-low: 0
    random-high: 0

  level_gate_distribution:
    # Determines how levels are distributed between level gate regions
    # Early: Earlier regions will have more levels than later regions
    # Even: Levels will be evenly distributed between all regions
    # Late: Later regions will have more levels than earlier regions
    early: 0
    even: 50
    late: 0

  level_gate_costs:
    # Determines how many emblems are required to unlock level gates
    low: 0
    medium: 0
    high: 50

  chao_garden_difficulty:
    # Determines the number of chao garden difficulty levels included. Easier difficulty settings means fewer chao garden checks
    # None: No Chao Garden Activities have checks
    # Beginner: Beginner Races
    # Intermediate: Beginner and Jewel Races
    # Expert: Beginner, Jewel, Challenge, Hero, and Dark Races
    none: 50
    beginner: 0
    intermediate: 0
    expert: 0

  include_chao_karate:
    # Determines whether the Chao Karate should be included as checks (Note: This setting requires purchase of the "Battle" DLC)
    false: 50
    true: 0

  chao_race_checks:
    # Determines which Chao Races grant checks
    # All: Each individual race grants a check
    # Prize: Only the races which grant Chao Toys grant checks (final race of each Beginner and Jewel cup, 4th, 8th, and
    #        12th Challenge Races, 2nd and 4th Hero and Dark Races)
    all: 50
    prize: 0

  junk_fill_percentage:
    # Replace a percentage of non-required emblems in the item pool with random junk items
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 100
    50: 50
    random: 0
    random-low: 0
    random-high: 0

  trap_fill_percentage:
    # Replace a percentage of junk items in the item pool with random traps
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 100
    0: 50
    random: 0
    random-low: 0
    random-high: 0

  omochao_trap_weight:
    # Likelihood of a receiving a trap which spawns several Omochao around the player
    none: 0
    low: 0
    medium: 50
    high: 0

  timestop_trap_weight:
    # Likelihood of a receiving a trap which briefly stops time
    none: 0
    low: 0
    medium: 50
    high: 0

  confusion_trap_weight:
    # Likelihood of a receiving a trap which causes the controls to be skewed for a period of time
    none: 0
    low: 0
    medium: 50
    high: 0

  tiny_trap_weight:
    # Likelihood of a receiving a trap which causes the player to become tiny
    none: 0
    low: 0
    medium: 50
    high: 0

  gravity_trap_weight:
    # Likelihood of a receiving a trap which increases gravity
    none: 0
    low: 0
    medium: 50
    high: 0

  exposition_trap_weight:
    # Likelihood of a receiving a trap which tells you the story
    none: 0
    low: 0
    medium: 50
    high: 0

  sadx_music:
    # Whether the randomizer will include Sonic Adventure DX Music in the music pool
    # SA2B: Only SA2B music will be played
    # SADX: Only SADX music will be played
    # Both: Both SA2B and SADX music will be played
    # NOTE: This option requires the player to own a PC copy of SADX and to follow the addition steps in the setup guide.
    sa2b: 50
    sadx: 0
    both: 0

  music_shuffle:
    # What type of Music Shuffle is used
    # Off: No music is shuffled.
    # Levels: Level music is shuffled.
    # Full: Level, Menu, and Additional music is shuffled.
    # Singularity: Level, Menu, and Additional music is all replaced with a single random song.
    none: 50
    levels: 0
    full: 0
    singularity: 0

  narrator:
    # Which menu narrator is used
    default: 50
    shadow: 0
    rouge: 0
    eggman: 0
    maria: 0
    secretary: 0
    omochao: 0
    amy: 0
    tails: 0
    knuckles: 0
    sonic: 0

  logic_difficulty:
    # What set of Upgrade Requirement logic to use
    # Standard: The logic assumes the "intended" usage of Upgrades to progress through levels
    # Hard: Some simple skips or sequence breaks may be required
    standard: 50
    hard: 0

  speed_mission_count:
    # The number of active missions to include for Sonic and Shadow stages
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 1
    # Maximum value is 5
    2: 50
    random: 0
    random-low: 0
    random-high: 0

  speed_mission_2:
    # Determines if the Sonic and Shadow 100 rings missions should be included
    false: 0
    true: 50

  speed_mission_3:
    # Determines if the Sonic and Shadow lost chao missions should be included
    false: 0
    true: 50

  speed_mission_4:
    # Determines if the Sonic and Shadow time trial missions should be included
    false: 0
    true: 50

  speed_mission_5:
    # Determines if the Sonic and Shadow hard missions should be included
    false: 0
    true: 50

  mech_mission_count:
    # The number of active missions to include for Tails and Eggman stages
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 1
    # Maximum value is 5
    2: 50
    random: 0
    random-low: 0
    random-high: 0

  mech_mission_2:
    # Determines if the Tails and Eggman 100 rings missions should be included
    false: 0
    true: 50

  mech_mission_3:
    # Determines if the Tails and Eggman lost chao missions should be included
    false: 0
    true: 50

  mech_mission_4:
    # Determines if the Tails and Eggman time trial missions should be included
    false: 0
    true: 50

  mech_mission_5:
    # Determines if the Tails and Eggman hard missions should be included
    false: 0
    true: 50

  hunt_mission_count:
    # The number of active missions to include for Knuckles and Rouge stages
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 1
    # Maximum value is 5
    2: 50
    random: 0
    random-low: 0
    random-high: 0

  hunt_mission_2:
    # Determines if the Knuckles and Rouge 100 rings missions should be included
    false: 0
    true: 50

  hunt_mission_3:
    # Determines if the Knuckles and Rouge lost chao missions should be included
    false: 0
    true: 50

  hunt_mission_4:
    # Determines if the Knuckles and Rouge time trial missions should be included
    false: 0
    true: 50

  hunt_mission_5:
    # Determines if the Knuckles and Rouge hard missions should be included
    false: 0
    true: 50

  kart_mission_count:
    # The number of active missions to include for Route 101 and 280
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 1
    # Maximum value is 5
    2: 50
    random: 0
    random-low: 0
    random-high: 0

  kart_mission_2:
    # Determines if the Route 101 and 280 100 rings missions should be included
    false: 0
    true: 50

  kart_mission_3:
    # Determines if the Route 101 and 280 avoid cars missions should be included
    false: 0
    true: 50

  kart_mission_4:
    # Determines if the Route 101 and 280 avoid walls missions should be included
    false: 0
    true: 50

  kart_mission_5:
    # Determines if the Route 101 and 280 hard missions should be included
    false: 0
    true: 50

  cannons_core_mission_count:
    # The number of active missions to include for Cannon's Core
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 1
    # Maximum value is 5
    2: 50
    random: 0
    random-low: 0
    random-high: 0

  cannons_core_mission_2:
    # Determines if the Cannon's Core 100 rings mission should be included
    false: 0
    true: 50

  cannons_core_mission_3:
    # Determines if the Cannon's Core lost chao mission should be included
    false: 0
    true: 50

  cannons_core_mission_4:
    # Determines if the Cannon's Core time trial mission should be included
    false: 0
    true: 50

  cannons_core_mission_5:
    # Determines if the Cannon's Core hard mission should be included
    false: 0
    true: 50

  death_link:
    # When you die, everyone dies. Of course the reverse is true too.
    false: 50
    true: 0
