# Q. What is this file?
# A. This file contains options which allow you to configure your multiworld experience while allowing
#    others to play how they want as well.
#
# Q. How do I use it?
# A. The options in this file are weighted. This means the higher number you assign to a value, the
#    more chances you have for that option to be chosen. For example, an option like this:
#
#    map_shuffle:
#      on: 5
#      off: 15
#
#    Means you have 5 chances for map shuffle to occur, and 15 chances for map shuffle to be turned
#    off.
#
# Q. I've never seen a file like this before. What characters am I allowed to use?
# A. This is a .yaml file. You are allowed to use most characters.
#    To test if your yaml is valid or not, you can use this website:
#        http://www.yamllint.com/
#    You can also verify your Archipelago settings are valid at this site:
#        https://archipelago.gg/check

# Your name in-game. Spaces will be replaced with underscores and there is a 16-character limit.
#     {player} will be replaced with the player's slot number.
#     {PLAYER} will be replaced with the player's slot number, if that slot number is greater than 1.
#     {number} will be replaced with the counter value of the name.
#     {NUMBER} will be replaced with the counter value of the name, if the counter value is greater than 1.
name: Player{number}

# Used to describe your yaml. Useful if you have multiple files.
description: Default The Witness Template

game: The Witness
requires:
  version: 0.3.9 # Version of Archipelago required for this yaml to work as expected.

The Witness:
  progression_balancing:
    # A system that can move progression earlier, to try and prevent the player from getting stuck and bored early.
    # A lower setting means more getting stuck. A higher setting means less getting stuck.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 99
    random: 0
    random-low: 0
    random-high: 0
    disabled: 0 # equivalent to 0
    normal: 50 # equivalent to 50
    extreme: 0 # equivalent to 99

  accessibility:
    # Set rules for reachability of your items/locations.
    # Locations: ensure everything can be reached and acquired.
    # Items: ensure all logically relevant items can be acquired.
    # Minimal: ensure what is needed to reach your goal can be acquired.
    locations: 0
    items: 50
    minimal: 0

  local_items:
    # Forces these items to be in their native world.
    []

  non_local_items:
    # Forces these items to be outside their native world.
    []

  start_inventory:
    # Start with these items.
    {}

  start_hints:
    # Start with these item's locations prefilled into the !hint command.
    []

  start_location_hints:
    # Start with these locations and their item prefilled into the !hint command
    []

  exclude_locations:
    # Prevent these locations from having an important item
    []

  priority_locations:
    # Prevent these locations from having an unimportant item
    []

  item_links:
    # Share part of your item pool with other players.
    []

  puzzle_randomization:
    # Puzzles in this randomizer are randomly generated. This setting changes the difficulty/types of puzzles.
    sigma_normal: 50
    sigma_expert: 0
    none: 0

  shuffle_symbols:
    # You will need to unlock puzzle symbols as items to be able to solve the panels that contain those symbols.
    # If you turn this off, there will be no progression items in the game unless you turn on door shuffle.
    false: 0
    true: 50

  shuffle_doors:
    # If on, opening doors will require their respective "keys".
    # If set to "panels", those keys will unlock the panels on doors.
    # In "doors_simple" and "doors_complex", the doors will magically open by themselves upon receiving the key.
    # The last option, "max", is a combination of "doors_complex" and "panels".
    none: 50
    panels: 0
    doors_simple: 0
    doors_complex: 0
    max: 0

  shuffle_lasers:
    # If on, the 11 lasers are turned into items and will activate on their own upon receiving them.
    # Note: There is a visual bug that can occur with the Desert Laser. It does not affect gameplay - The Laser can still
    # be redirected as normal, for both applications of redirection.
    false: 50
    true: 0

  disable_non_randomized_puzzles:
    # Disables puzzles that cannot be randomized.
    # This includes many puzzles that heavily involve the environment, such as Shadows, Monastery or Orchard.
    # The lasers for those areas will be activated as you solve optional puzzles throughout the island.
    false: 50
    true: 0

  shuffle_discarded_panels:
    # Add Discarded Panels into the location pool.
    # Solving certain Discarded Panels may still be necessary to beat the game, even if this is off.
    false: 50
    true: 0

  shuffle_vault_boxes:
    # Vault Boxes will have items on them.
    false: 50
    true: 0

  shuffle_EPs:
    # Add Environmental/Obelisk Puzzles into the location pool.
    # In "individual", every Environmental Puzzle sends an item.
    # In "obelisk_sides", completing every puzzle on one side of an Obelisk sends an item.
    # Note: In Obelisk Sides, any EPs excluded through another setting will be counted as pre-completed on their Obelisk.
    off: 50
    individual: 0
    obelisk_sides: 0

  EP_difficulty:
    # When "Shuffle Environmental Puzzles" is on, this setting governs which EPs are eligible for the location pool.
    # On "eclipse", every EP in the game is eligible, including the 1-hour-long "Theater Eclipse EP".
    # On "tedious", Theater Eclipse EP is excluded from the location pool.
    # On "normal", several other difficult or long EPs are excluded as well.
    normal: 50
    tedious: 0
    eclipse: 0

  shuffle_postgame:
    # Adds locations into the pool that are guaranteed to become accessible after or at the same time as your goal.
    # Use this if you don't play with release on victory. IMPORTANT NOTE: The possibility of your second
    # "Progressive Dots" showing up in the Caves is ignored, they will still be considered "postgame" in base settings.
    false: 50
    true: 0

  victory_condition:
    # Change the victory condition from the original game's ending (elevator) to beating the Challenge
    # or solving the mountaintop box, either using the short solution
    # (7 lasers or whatever you've changed it to) or the long solution (11 lasers or whatever you've changed it to).
    elevator: 50
    challenge: 0
    mountain_box_short: 0
    mountain_box_long: 0

  mountain_lasers:
    # Sets the amount of beams required to enter the final area.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 1
    # Maximum value is 7
    7: 50
    random: 0
    random-low: 0
    random-high: 0

  challenge_lasers:
    # Sets the amount of beams required to enter the Caves through the Mountain Bottom Floor Discard.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 1
    # Maximum value is 11
    11: 50
    random: 0
    random-low: 0
    random-high: 0

  early_secret_area:
    # Opens the Mountainside shortcut to the Caves from the start.
    # (Otherwise known as "UTM", "Caves" or the "Challenge Area")
    false: 50
    true: 0

  trap_percentage:
    # Replaces junk items with traps, at the specified rate.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 100
    20: 50
    random: 0
    random-low: 0
    random-high: 0

  puzzle_skip_amount:
    # Adds this number of Puzzle Skips into the pool, if there is room. Puzzle Skips let you skip one panel.
    # Works on most panels in the game - The only big exception is The Challenge.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 30
    10: 50
    random: 0
    random-low: 0
    random-high: 0

  hint_amount:
    # Adds hints to Audio Logs. Hints will have the same number of duplicates, as many as will fit. Remaining Audio
    # Logs will have junk hints.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 0
    # Maximum value is 49
    10: 50
    random: 0
    random-low: 0
    random-high: 0
